version: '3'

services:
  api:
    build: .
    ports:
      - "8000:7860"
    volumes:
      - .:/app
      - sqlite_data:/data  # Mount a volume for persistent SQLite data
    environment:
      - PORT=7860
      - HF_HOME=/app/.cache/huggingface
      - DATABASE_PATH=/data/emails.db
    restart: unless-stopped

volumes:
  sqlite_data:  # Define the volume for SQLite database