version: '3'

services:
  api:
    build: .
    ports:
      - "8000:7860"
    volumes:
      - .:/app
    environment:
      - PORT=7860
      - HF_HOME=/app/.cache/huggingface
    restart: unless-stopped